-- CreateTable
CREATE TABLE IF NOT EXISTS aikon_db.users (
    id BIGINT(11) NOT NULL AUTO_INCREMENT,
    name VARCHAR(191) NOT NULL,
    mail VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
)ENGINE=INNODB DEFAULT CHARSET=utf8mb4;